// This file will be auto-generated by Payload CMS
// For now, we'll define basic types that match our collections

export interface Category {
  id: string
  name: string
  description?: string
  slug: string
  order: number
  icon?: string
  createdAt: string
  updatedAt: string
}

export interface Vendor {
  id: string
  name: string
  logo?: Media
  website?: string
  rssUrl?: string
  description?: string
  createdAt: string
  updatedAt: string
}

export interface Product {
  id: string
  name: string
  description?: any // Rich text content
  features?: Array<{ feature: string }>
  category: Category | string
  vendor: Vendor | string
  image?: Media
  datasheet?: Media
  order: number
  active: boolean
  createdAt: string
  updatedAt: string
}

export interface Page {
  id: string
  title: string
  slug: string
  content?: any // Rich text content
  type: 'hero' | 'about' | 'contact' | 'page'
  images?: Array<{ image: Media }>
  createdAt: string
  updatedAt: string
}

export interface NewsArticle {
  id: string
  title: string
  summary?: string
  content?: any // Rich text content
  publishedAt: string
  vendor?: Vendor | string
  sourceUrl?: string
  image?: Media
  tags?: Array<{ tag: string }>
  createdAt: string
  updatedAt: string
}

export interface Media {
  id: string
  alt?: string
  filename: string
  mimeType: string
  filesize: number
  width?: number
  height?: number
  sizes?: {
    thumbnail?: {
      url: string
      width: number
      height: number
    }
    card?: {
      url: string
      width: number
      height: number
    }
    tablet?: {
      url: string
      width: number
      height: number
    }
  }
  url: string
  createdAt: string
  updatedAt: string
}

export interface User {
  id: string
  email: string
  role: 'admin' | 'editor'
  createdAt: string
  updatedAt: string
}